# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Maven Publishing
GROUP=io.featurama
VERSION_NAME=1.0.0

# POM
POM_NAME=Featurama Android SDK
POM_DESCRIPTION=Official Featurama SDK for Android (coming soon for MVP)
POM_URL=https://github.com/featurama/featurama-android
POM_SCM_URL=https://github.com/featurama/featurama-android
POM_SCM_CONNECTION=scm:git:git://github.com/featurama/featurama-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/featurama/featurama-android.git
POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_DEVELOPER_ID=featurama
POM_DEVELOPER_NAME=Featurama
